### ISSUE TITLE
no map

### ISSUE THREAD

**Issue by pa794** [jeffreykemp/jk64-plugin-reportmap#32] opened 2016-11-04 15:41 UTC
plugin does not show map.  i have installed version 0.7.2

what are required attributes for map to display?

**Comment by jeffreykemp** [comment] 2016-11-05 00:00
Thank you for giving this plugin a try!

The minimum attributes is a query to run (e.g. select lat, lng, name, id from mytable) and a height (which is defaulted to 400).

I've updated the online demo to 0.7.2 and added a "Minimal Test" page and it seems to work for me:
[https://apex.oracle.com/pls/apex/f?p=15181:9](https://apex.oracle.com/pls/apex/f?p=15181:9)


Please check your browser's debug console for errors and if you can post a link to a demo online reproducing your problem I'd be happy to have a look.

Thanks, please keep me posted on your progress and let me know if I can help further.
Jeff

**Comment by jeffreykemp** [comment] 2016-11-15 08:44
Closing - unable to reproduce

**Closed by jeffreykemp** 2016-11-15 08:44 UTC
