### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by SmileyMan** [jeffreykemp/jk64-plugin-reportmap#76] opened 2019-08-06 11:56 UTC
Plugin does not work in IE11

Just open Demo in IE11. Maps do not render and logs JavaScript errors

*Sry company I work for still uses this old browser.

SCRIPT1006: Expected ')'
File: jk64reportmap_r1.min.js, Line: 1, Column: 7448

jQuery.Deferred exception: Object doesn't support property or method 'reportmap' TypeError: Object doesn't support property or method 'reportmap'

SCRIPT438: Object doesn't support property or method 'reportmap'
File: desktop_all.min.js, Line: 2, Column: 31040

**Comment by jeffreykemp** [comment] 2019-08-06 12:52
Thanks for reporting this. I've reproduced this in IE11. I'll work on a fix.

**Comment by jeffreykemp** [comment] 2019-08-06 13:21
Turns out IE 11 does not support default parameters for javascript functions.

This will be resolved by v1.0.2.

**Comment by SmileyMan** [comment] 2019-08-06 13:24
Thank you.

**Comment by jeffreykemp** [comment] 2019-08-06 13:24
SmileyMan, please download and install the plugin from this branch:

https://github.com/jeffreykemp/jk64-plugin-reportmap/tree/Patch-1-0-2

and confirm whether it works for you now.

Note: if you need the pre-18.2 version, I haven't updated the backport yet. If so, let me know.

Thanks

**Comment by SmileyMan** [comment] 2019-08-19 21:10
Hi. Sorry been working away.

I have to use 5.003 which is the version we have on our platform at the moment.

**Comment by jeffreykemp** [comment] 2019-08-20 00:37
No problem - I've backported the fix to 5.0.3, please download the updated plugin from here:

https://github.com/jeffreykemp/jk64-plugin-reportmap/tree/Patch-1-0-2/backport

**Comment by SmileyMan** [comment] 2019-08-27 15:19
Can confirm this now works with IE11

**Comment by jeffreykemp** [comment] 2020-01-08 02:58
Merged into v1.1

**Comment by jeffreykemp** [comment] 2020-02-20 05:26
Fixed in Release 1.1

**Closed by jeffreykemp** 2020-02-20 05:26 UTC
Labels: bug
